Repository brandontran1220/UCRPurity, pull requests merged in 2025-05, with the labels that each got.

#14 Brandontran1220/board comp
  public/board/aaron_huynh.webp
  public/board/brandon_tran.webp
  public/board/dillion_huynh.webp
  public/board/tony_zhou.webp
  public/board/zach_nobunaga.webp
  src/app/board/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/board/boardCard.tsx
  src/components/board/boards.tsx
  src/data/Board.ts
Labels: ready to review

#13 added error component
  public/sadRice.svg
  src/app/not-found.tsx
  src/components/error/error.tsx
Labels: ready to review

#18 Add background and fixed error page
  public/scotty.svg
  src/app/layout.tsx
  src/components/background.tsx
  src/components/error/error.tsx
Labels: ready to review

#16 Navbar
  src/app/layout.tsx
  src/components/NavBar.tsx
  src/components/Title.tsx
  src/components/background.tsx
Labels: ready to review

#31 Result Page
  public/dirtyRice.svg
  public/neutralRice.svg
  public/sillyRice.svg
  src/app/result/page.tsx
  src/components/result.tsx
Labels: ready to review

#55 added mobile responsiveness for background
  src/components/background.tsx
Labels: ready to review

#52 Home mobile
  src/components/home/Title.tsx
  src/components/home/descript.tsx
Labels: ready to review

#46 added navbar mobile responsiveness
  src/app/page.tsx
  src/components/NavBar.tsx
  src/components/board/boardDescript.tsx
  src/components/board/boardTitle.tsx
Labels: address comments

#58 Brandontran1220/log in
  .github/workflows/pull-request.yaml
  middleware.ts
  next.config.js
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/login/page.tsx
  src/components/ConditionalLayout.tsx
  src/components/NavBar.tsx
  src/contexts/AuthContext.tsx
  src/utils/supabase/client.ts
  src/utils/supabase/middleware.ts
Labels: bug

#61 Track scores for every registered user
  DATABASE_TROUBLESHOOTING.md
  SCORE_IMPLEMENTATION.md
  setup_database.sql
  src/app/admin-test/page.tsx
  src/app/admin/page.tsx
  src/components/home/questions.tsx
  src/contexts/AuthContext.tsx
  src/utils/database.ts
  src/utils/saveScore.ts
Labels: ready to review

#68 added dropdown lore on stats page
  src/app/stats/page.tsx
  src/components/stats/StatsLore.tsx
Labels: ready to review

#79 Add analytics and text style
  package-lock.json
  package.json
  src/app/layout.tsx
  src/components/stats/StatsTitle.tsx
Labels: ready to review
